blank_issues_enabled: false
contact_links:
  - name: 📧 Contacto Directo
    url: mailto:soporte@thesynaptek.com
    about: Contacta directamente con el equipo de Synaptek para consultas urgentes o privadas.
